config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('distribution.urls', namespace='distribution')),
]

distribution/urls.py
from django.urls import path

from distribution.apps import DistributionConfig
from distribution.views import MailingSettingsDetailView, MailingSettingsListView, MailingSettingsCreateView, \
    MailingSettingsDeleteView, MailingSettingsUpdateView, ClientListView, ClientCreateView, ClientUpdateView, \
    LogListView

app_name = DistributionConfig.name

urlpatterns = [
    path('log', LogListView.as_view(), name='log_list'),
    path('clients/edit/<int:pk>/', ClientUpdateView.as_view(), name='edit_client'),
    path('clients/create', ClientCreateView.as_view(), name='create_client'),
    path('clients', ClientListView.as_view(), name='clients_list'),
    path('distribution/<int:pk>/', MailingSettingsDetailView.as_view(), name='distribution_detail'),
    path('delete/<int:pk>/', MailingSettingsDeleteView.as_view(), name='distribution_delete'),
    path('', MailingSettingsListView.as_view(), name='distribution_list'),
    path('create', MailingSettingsCreateView.as_view(), name='create_distribution'),
    path('edit/<int:pk>/', MailingSettingsUpdateView.as_view(), name='distribution_edit'),
]

distribution/models.py
from datetime import timedelta, time

from django.db import models

NULLABLE = {'null': True, 'blank': True}


class Client(models.Model):
    FIO = models.CharField(max_length=150, verbose_name='ФИО')
    email = models.EmailField(max_length=150, verbose_name='почта', unique=True)
    comment = models.TextField(verbose_name='комментирий', **NULLABLE)

    def __str__(self):
        return f"{self.FIO} {self.email}"

    class Meta:
        verbose_name = "клиент"
        verbose_name_plural = "клиенты"
        ordering = ('FIO',)


class MailingSettings(models.Model):
    DAILY = "Раз в день"
    WEEKLY = "Раз в неделю"
    MONTHLY = "Раз в месяц"

    PERIODICITY_CHOICES = [
        (DAILY, "Раз в день"),
        (WEEKLY, "Раз в неделю"),
        (MONTHLY, "Раз в месяц"),
    ]

    CREATED = 'Создана'
    STARTED = 'Запущена'
    COMPLETED = 'Завершена'

    STATUS_CHOICES = [
        (COMPLETED, "Завершена"),
        (CREATED, "Создана"),
        (STARTED, "Запущена"),
    ]

    start_time = models.DateTimeField(verbose_name='время начала рассылки')
    end_time = models.DateTimeField(verbose_name='время окончания рассылки')
    periodicity = models.CharField(max_length=50, verbose_name='периодичность', choices=PERIODICITY_CHOICES)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES, default=CREATED, verbose_name='статус рассылки')

    clients = models.ManyToManyField(Client, verbose_name='клиенты рассылки')

    def __str__(self):
        return f'time: {self.start_time} - {self.end_time}, periodicity: {self.periodicity}, status: {self.status}'

    class Meta:
        verbose_name = 'настройки рассылки'
        verbose_name_plural = 'настройки рассылки'


class Message(models.Model):
    title = models.CharField(max_length=100, verbose_name='тема письма')
    text = models.TextField(verbose_name='тело письма')
    mailing_list = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='рассылка',
                                     related_name='messages', **NULLABLE)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'сообщение'
        verbose_name_plural = 'сообщения'


class Log(models.Model):
    time = models.DateTimeField(verbose_name='дата и время последней попытки', auto_now_add=True)
    status = models.BooleanField(verbose_name='статус попытки')
    server_response = models.CharField(verbose_name='ответ почтового сервера', **NULLABLE)

    mailing_list = models.ForeignKey(MailingSettings, on_delete=models.CASCADE, verbose_name='рассылка')
    client = models.ForeignKey(Client, on_delete=models.CASCADE, verbose_name='клиент рассылки', **NULLABLE)

    def __str__(self):
        return f'{self.time} {self.status}'

    class Meta:
        verbose_name = 'лог'
        verbose_name_plural = 'логи'

distribution/forms.py
from django.forms import ModelForm

from distribution.models import Message, MailingSettings, Client


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingSettingsForm(StyleFormMixin, ModelForm):
    class Meta:
        model = MailingSettings
        fields = ('start_time', 'end_time', 'periodicity', 'status', 'clients',)


class MessageForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Message
        fields = ('title', 'text',)


class ClientForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Client
        fields = ('FIO', 'email', 'comment',)

distribution/views.py
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, ListView, DetailView, DeleteView, UpdateView
from django.forms import inlineformset_factory

from distribution.forms import MessageForm, MailingSettingsForm, ClientForm
from distribution.models import Client, MailingSettings, Message, Log


class ClientListView(ListView):
    model = Client


class ClientCreateView(CreateView, ClientForm):
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('distribution:clients_list')


class ClientUpdateView(CreateView, UpdateView):
    model = Client
    form_class = ClientForm

    def get_success_url(self):
        return reverse('distribution:clients_list')


class MailingSettingsDetailView(DetailView):
    model = MailingSettings


class MailingSettingsListView(ListView):
    model = MailingSettings

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        context_data['all'] = context_data['object_list'].count()
        context_data['active'] = context_data['object_list'].filter(status=MailingSettings.STARTED).count()

        mailing_list = context_data['object_list'].prefetch_related('clients')
        clients = set()
        [[clients.add(client.email) for client in mailing.clients.all()] for mailing in mailing_list]
        context_data['clients_count'] = len(clients)
        return context_data


class MailingSettingsCreateView(CreateView):
    model = MailingSettings
    form_class = MailingSettingsForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(MailingSettings, Message, extra=1, form=MessageForm)

        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST)
        else:
            context_data['formset'] = MessageFormset()

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('distribution:distribution_list')


class MailingSettingsDeleteView(DeleteView):
    model = MailingSettings

    def get_success_url(self):
        return reverse('distribution:distribution_list')


class MailingSettingsUpdateView(UpdateView):
    model = MailingSettings
    form_class = MailingSettingsForm

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        MessageFormset = inlineformset_factory(MailingSettings, Message, extra=1, form=MessageForm)

        if self.request.method == 'POST':
            context_data['formset'] = MessageFormset(self.request.POST, instance=self.object)
        else:
            context_data['formset'] = MessageFormset(instance=self.object)

        return context_data

    def form_valid(self, form):
        formset = self.get_context_data()['formset']
        self.object = form.save()
        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('distribution:distribution_detail', args=[self.object.pk])


class LogListView(ListView):
    model = Log

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        context_data['all'] = context_data['object_list'].count()
        context_data['success'] = context_data['object_list'].filter(status=True).count()
        context_data['error'] = context_data['object_list'].filter(status=False).count()

        return context_data

distribution/templates/distribution/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{{ title }}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet"
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">

</head>
{% include 'distribution/includes/inc_main_menu.html' %}

{% block content %}
{% endblock %}

<footer class="pt-4 my-md-5 pt-md-5 border-top text-center">
    <div class="row">
        <div class="col-12 col-md">
            SkyStore
            <small class="d-block mb-3 text-muted">&copy; 2023</small>
        </div>
        <div class="col-6 col-md">
            <h5>Категории</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Рассылки</a></li>
                <li><a class="text-muted" href="#">Телеграм боты</a></li>
                <li><a class="text-muted" href="#">Полезные утилиты</a></li>
                <li><a class="text-muted" href="#">Веб-приложения</a></li>
                <li><a class="text-muted" href="#">Микросервисы</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>Дополнительно</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="#">Мы пишем</a></li>
            </ul>
        </div>
        <div class="col-6 col-md">
            <h5>О нас</h5>
            <ul class="list-unstyled text-small">
                <li><a class="text-muted" href="/contacts/">Контакты</a></li>
                <li><a class="text-muted" href=""</li>
            </ul>
        </div>
    </div>
</footer>
</div>

<script src="/static/js/bootstrap.bundle.min.js"></script>
</body>
</html>

distribution/templates/distribution/client_form.html
{% extends "distribution/base.html" %}
{% block content %}
<form method="post" class="row">
    {% csrf_token %}
    <div class="col-md-6">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h3>Настройки рассылки</h3>
            </div>
            <div class="card-body">
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                    Изменить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
                <a href="{% url 'distribution:clients_list' %}" class="btn btn-warning">Отмена</a>
            </div>
        </div>
    </div>
</form>
{% endblock %}

distribution/templates/distribution/client_list.html
{% extends "distribution/base.html" %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-1">Список имеющихся клиентов</h1>
</div>


<div class="container col-10">
    <div class="card">
        <div class="card-header text-center">
            <h1>Клиенты</h1>
        </div>
        <div class="card-body">
            <div class="col-12">
                <table class="table text-center">
                    <tr>
                        <th><h4>ФИО клиента</h4></th>
                        <th><h4>email клиента</h4></th>
                        <th><h4>Комментарий</h4></th>
                        <th><h4>Исправить данные</h4></th>
                    </tr>
                    {% for object in object_list %}
                    <tr>
                        <td><h4>{{ object.FIO }}</h4></td>
                        <td><h4>{{ object.email }}</h4></td>
                        <td><h4>{{ object.comment }}</h4></td>
                        <td><h4><a class="btn btn-lg btn-warning"
                                   href="{% url 'distribution:edit_client' object.pk %}">Исправить</a></h4></td>
                        {% endfor %}
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="row text-right mt-4">
        <div class="col-12">
            <a class="p-2 btn btn-outline-primary btn-block btn-lg" href="{% url 'distribution:create_client' %}">Создать
                нового клиента</a>
        </div>
    </div>
    {% endblock %}

distribution/templates/distribution/includes/inc_main_menu.html
<div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
    <h5 class="my-0 mr-md-auto font-weight-normal">Сервис рассылок сообщений</h5>
    <nav class="ms-5">
        <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:clients_list' %}">Список клиентов</a>
        <a class="p-2 btn btn-outline-primary" href="/">Рассылки</a>
        <a class="p-2 btn btn-outline-primary" href="{% url 'distribution:log_list' %}">Журнал рассылок</a>
    </nav>
</div>

distribution/templates/distribution/log_list.html
{% extends "distribution/base.html" %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-1">Журнал рассылок</h1>
</div>

<div class="container col-8 mt-2 mb-5">
    <div class="card">
        <div class="card-header text-center">
            <h1>Статистика</h1>
        </div>
        <div class="card-body">
            <div class="row text-center ">
                <div class="col-12">
                    <table class="table">
                        <tr>
                            <th><h4>Количество отправленных писем</h4></th>
                            <th><h4>Количество успешно отправленных писем</h4></th>
                            <th><h4>Количество ошибок</h4></th>
                        </tr>
                        <body>
                        <tr>
                            <td><h4>{{ all }}</h4></td>
                            <td><h4>{{ success }}</h4></td>
                            <td><h4>{{ error }}</h4></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container col-10">
    <div class="card">
        <div class="card-header text-center">
            <h1>Рассылки</h1>
        </div>
        <div class="card-body">
            <div class="col-12">
                <table class="table text-center">
                    <tr>
                        <th><h4>Время рассылки</h4></th>
                        <th><h4>Данные рассылки</h4></th>
                        <th><h4>Получатель рассылки</h4></th>
                        <th><h4>Статус рассылки</h4></th>
                    </tr>
                    {% for object in object_list %}
                    <tr>
                        <td><h4>{{ object.time }}</h4></td>
                        <td><h4>{{ object.mailing_list }}</h4></td>
                        <td><h4>{{ object.client }}</h4></td>
                        <td><h4>
                            {% if object.status %}
                            <p style="color:green">Успешно</p>
                            {% else %}
                            <p style="color:red">Ошибка</p>
                            {% endif %}
                        </h4></td>
                        {% endfor %}
                    </tr>
                </table>
            </div>
        </div>
    </div>
    {% endblock %}

distribution/templates/distribution/mailingsettings_confirm_delete.html
{% extends "distribution/base.html" %}
{% block content %}
<div class="container">
    <div class="row text-center">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        <p>Хотите удалить рассылку №{{ object.pk }}?</p>
                        <button type="submit" class="btn btn-success">Подтвердить</button>
                        <a href="{% url 'distribution:distribution_list' %}" class="btn btn-warning">Отмена</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

distribution/templates/distribution/mailingsettings_detail.html
{% extends "distribution/base.html" %}
{% block content %}
<div class="col-12">
    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
        <h1 class="display-1">Рассылка номер {{ object.pk }}</h1>
        <p class="lead">Подробное описание рассылки</p>
    </div>
</div>


<div class="col-12 text-center">
    <table class="table table-striped">
        <tr>
            <th>Начало рассылки</th>
            <th>Конец рассылки</th>
            <th>Переодичность рассылки</th>
            <th>Статус рассылки</th>
            <th>Участники рассылки</th>
        </tr>
        <tr>
            <td><h4>{{ object.start_time }}</h4></td>
            <td><h4>{{ object.end_time }}</h4></td>
            <td><h4>{{ object.periodicity }}</h4></td>
            <td><h4>{{ object.status }}</h4></td>
            <td><h4>{% for client_item in object.clients.all %}
                {{ client_item.email }}
                {% endfor %}
            </h4></td>
        </tr>
    </table>
    <div align="center"><a class="btn btn-outline-primary btn-lg" href="{% url 'distribution:distribution_list' %}">Вернуться
    на главную страницу</a></div>


    {% endblock %}

distribution/templates/distribution/mailingsettings_form.html
{% extends "distribution/base.html" %}
{% block content %}
<form method="post" class="row">
    {% csrf_token %}
    <div class="col-md-6">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h3>Настройки рассылки</h3>
            </div>
            <div class="card-body">
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    {% if object %}
                    Изменить
                    {% else %}
                    Создать
                    {% endif %}
                </button>
                <a href="{% url 'distribution:distribution_list' %}" class="btn btn-warning">Отмена</a>
            </div>
        </div>
    </div>
    <div class="col-md-6">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h3>Сообщения</h3>
            </div>
            <div class="card-body">
                {{ formset.management_form }}
                {% for form in formset.forms %}
                {{ form.as_p }}
                {% if not forloop.last %}
                <hr>
                {% endif %}
                {% endfor %}
            </div>
        </div>
    </div>
</form>
{% endblock %}

distribution/templates/distribution/mailingsettings_list.html
{% extends "distribution/base.html" %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-1">Страница контроля рассылок</h1>
</div>

<div class="container col-8 mt-2 mb-5">
    <div class="card">
        <div class="card-header text-center">
            <h1>Статистика</h1>
        </div>
        <div class="card-body">
            <div class="row text-center ">
                <div class="col-12">
                    <table class="table">
                        <tr>
                            <th><h4>Количество рассылок</h4></th>
                            <th><h4>Количество активных рассылок</h4></th>
                            <th><h4>Количество уникальных клиентов</h4></th>
                        </tr>
                        <body>
                        <tr>
                            <td><h4>{{ all }}</h4></td>
                            <td><h4>{{ active }}</h4></td>
                            <td><h4>{{ clients_count }}</h4></td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container col-10">
    <div class="card">
        <div class="card-header text-center">
            <h1>Рассылки</h1>
        </div>
        <div class="card-body">
            <div class="col-12 text-center">
                <table class="table">
                    <tr>
                        <th><h4>Время рассылки</h4></th>
                        <th><h4>Статус рассылки</h4></th>
                        <th><h4>Переодичность рассылки</h4></th>
                        <th><h4>Подробности рассылки</h4></th>
                        <th><h4>Редактирование рассылки</h4></th>
                        <th><h4>Удаление рассылки</h4></th>
                    </tr>
                    {% for object in object_list %}
                    <tr>
                        <td><h4>{{ object.start_time }}</h4></td>
                        <td><h4>{{ object.status }}</h4></td>
                        <td><h4>{{ object.periodicity }}</h4></td>
                        <td><h4>
                            <a href="{% url 'distribution:distribution_detail' object.pk %}" class="btn btn-lg btn-primary">Полная
                                информация</a>
                        </h4></td>
                        <td><h4>
                            <a class="btn btn-lg btn-warning"
                               href="{% url 'distribution:distribution_edit' object.pk %}">Исправить</a>
                        </h4></td>
                        <td><h4>
                            <a class="btn btn-lg btn-danger"
                               href="{% url 'distribution:distribution_delete' object.pk %}">Удалить</a>
                        </h4></td>
                        {% endfor %}
                    </tr>
                </table>
            </div>
        </div>
    </div>
    <div class="row text-right mt-4">
        <div class="col-12">
            <a class="p-2 btn btn-outline-primary btn-block btn-lg" href="{% url 'distribution:create_distribution' %}">Создать
                новую рассылку</a>
        </div>
    </div>
    {% endblock %}